#define N_PLAT_NLM                                /* Define dest. platform */

#include <nwconio.h>                              /* ConsolePrintf */

#include "implicit_nlm_defs.h"
#include "vgamode.c"
#include "modes.c"                                /* set_text_mode() */
#include "vga_util.h"                             /* save/restore_text_buffer, save/restore_vga_palette */
#include "generated/hello_vga_pic.h"               /* embedded_pic_pixels/palette, generated by pcx_to_c.py */
#include "adlib_util.h"                            /* adlib_play_song, adlib_silence */
#include "generated/dune0_song4.h"                 /* dune0_song4_events, generated by music/adl_to_c.py */

#define CP437_SMILEY_FACE_CHAR 0x01

/*
 * example for 320x200 VGA
 * Copied from https://wiki.osdev.org/Drawing_In_a_Linear_Framebuffer
 */
void putpixel(int pos_x, int pos_y, unsigned char VGA_COLOR)
{
    unsigned char* location = (unsigned char*)0xA0000 + 320 * pos_y + pos_x;
    *location = VGA_COLOR;
}

/**
 * Blit the embedded picture (see hello_vga_pic.h) into the mode 13h linear framebuffer.
 */
void draw_embedded_picture() {
  unsigned char *vram = (unsigned char *)0xA0000;
  int i;
  for (i = 0; i < EMBEDDED_PIC_WIDTH * EMBEDDED_PIC_HEIGHT; i++) {
    vram[i] = embedded_pic_pixels[i];
  }
}

/**
 * With thanks to https://dev.to/frosnerd/writing-my-own-vga-driver-22nn
 */
void set_vga_cursor(int offset) {

  #define VGA_CTRL_REGISTER 0x3d4
  #define VGA_DATA_REGISTER 0x3d5
  #define VGA_OFFSET_LOW 0x0f
  #define VGA_OFFSET_HIGH 0x0e

  offset /= 2;
    outp(VGA_CTRL_REGISTER, VGA_OFFSET_HIGH);
    outp(VGA_DATA_REGISTER, (unsigned char) (offset >> 8));
    outp(VGA_CTRL_REGISTER, VGA_OFFSET_LOW);
    outp(VGA_DATA_REGISTER, (unsigned char) (offset & 0xff));
}

int
main (int argc, char **argv)
{
  int i;

  ConsolePrintf ("\rHello world! %c\n\n", CP437_SMILEY_FACE_CHAR);           /* print on system console */
  ConsolePrintf("\rBuild date: INSERT_TIMESTAMP_HERE\n");

  ConsolePrintf("\rArguments:\n");                  /* all arguments */
  for (i=0;i<argc;i++)
   ConsolePrintf("\rargv[%u]=\"%s\"\n",i, argv[i]);

  ConsolePrintf("\n\r"); // Make sure the command prompt starts at the beginning below an empty line when this application/module exits.

  putTextChars();
  int current_cursor_position = get_vga_cursor();
  ConsolePrintf ("\rCurrent cursor position: %d\n\n", current_cursor_position);
  // setVGACursor(320);

  /* turn off speaker */
  //outp (0x61,inp (0x61) & 0xFC);

  // Use VGA routines in modes.c
	// dump_state();
	// set_text_mode(1);
  // demo_graphics();
	// font512();

  const int delay_before_vga_switch_in_seconds = 3;
  ConsolePrintf("\n\rDelaying %d secs BEFORE switching to VGA graphics mode...\n\r", delay_before_vga_switch_in_seconds);
  delay(delay_before_vga_switch_in_seconds * 1000); // Delay x seconds.

  ConsolePrintf("\n\rSwitching to VGA graphics mode...\n\r");

  // Snapshot right before the switch (not the earlier current_cursor_position above, which is
  // stale by now - several more ConsolePrintf calls have moved the cursor since it was captured).
  int cursor_before_graphics = get_vga_cursor();
  save_text_buffer();
  save_vga_palette();

  // Switch to VGA graphics code using code in vgamode.c
  int mode_switching_result = init_graph_vga(320, 200, 1);

  if (mode_switching_result == 1) {
    ConsolePrintf("Switch to VGA graphics mode successful. (This text might not even be readable.)\n\r");

    // Force the DAC black and draw the picture *before* fading in, not after - the DAC still
    // holds whatever text mode left there (restored later via restore_vga_palette()) until we
    // explicitly set it, and it may hold stray non-black values for indices this picture uses
    // outside the 16 text mode actively drives; without this the picture would flash its real
    // colors for a moment before the fade-in loop got to them.
    set_vga_palette_black();
    draw_embedded_picture();

    // 64 steps matches the VGA DAC's own 6-bit (0-63) per-channel resolution - the ceiling of
    // what the hardware can actually render, more steps than that buys nothing.
    const int fade_steps = 64;
    const int fade_step_delay_ms = 20;
    fade_palette(embedded_pic_palette, 256, fade_steps, fade_step_delay_ms, 1);

    // adlib_play_song() blocks (via delay()) for the whole song, so the fade-out and text-mode
    // switch below can't happen until the jingle has actually finished playing.
    {
      const struct Opl2Song intro_jingle = {4, DUNE0_SONG4_EVENT_COUNT, DUNE0_SONG4_TICK_COUNT,
                                             dune0_song4_events};
      adlib_play_song(&intro_jingle);
      adlib_silence();
    }

    fade_palette(embedded_pic_palette, 256, fade_steps, fade_step_delay_ms, 0);

    // Restore 80x25 text mode before exiting, so the console is usable again without a VM reset
    // (set_text_mode() from modes.c) - see docs/qemu-vm-debugging.md's "Existing groundwork" note.
    set_text_mode(0);
    restore_text_buffer();
    restore_vga_palette();

    // set_text_mode()'s canned CRTC register table hardcodes the cursor-location registers to a
    // fixed value, stomping wherever NetWare's own console had it (its prompt). Put it back.
    set_vga_cursor(cursor_before_graphics);

    ConsolePrintf("\rRestored 80x25 text mode.\n\r");
  } else {
    ConsolePrintf("Switch to VGA graphics mode failed.\n\r");
  }

  return 0;                                       /* exit NLM */
}
